server:

  port: 9092

spring:

   application:

      name: order-server

   datasource:

     driver-class-name: com.mysql.jdbc.Driver

     username: root

     password: root123

     url: jdbc:mysql://localhost:3306/myrbac?characterEncoding=utf-8&userSSL=false
     

eureka:

  client:

    service-url:

      defaultZone: http://localhost:9090/eureka
