server:

  port: 9092

spring:

   application:

      name: order-server

   datasource:

     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/j1807db?characterEncoding=utf-8&serverTimezone=UTC
     password: root123
     username: root
     
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jeffrey.pojo
eureka:

  client:

    service-url:

      defaultZone: http://localhost:9090/eureka
